// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "react-amplified-20191202192711-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://react-amplified-20191202192711-hostingbucket-dev.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:57231b7f-88e3-4166-9617-804be0b3f60d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UsIG2mkzG",
    "aws_user_pools_web_client_id": "1ccfu0vfsla1js37rh1o2emohq",
    "oauth": {},
    "aws_user_files_s3_bucket": "react-amplified0907a1a60bb94e9eb91bdea83c9ec6cedev-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
